--- #YAML:1.0
name:               Linux-PipeMagic
version:            0.02
abstract:           Perl extension to use the zero copy IO syscalls
author:
    - Dave Lambley <cpan@davel.org.uk
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Slurp:  0
    File::Temp:   0
    Test::More:   0
requires:
    File::Slurp:  0
    File::Temp:   0
    Test::More:   0
resources:
    repository:  http://github.com/davel/Linux-PipeMagic
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
